# Copyright (c) Digital Imaging Software Solutions, INC
# Dan Sheffner Dan@Sheffner.org
# All rights reserved.
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish, dis-
# tribute, sublicense, and/or sell copies of the Software, and to permit
# persons to whom the Software is furnished to do so, subject to the fol-
# lowing conditions:
#
# The above copyright notice and this permission notice shall be included
# in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
# OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABIL-
# ITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT
# SHALL THE AUTHOR BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

FROM ubuntu:rolling

# MAINTAINER Dan Sheffner
# this is going to the base container for allot of other containers
# it is going to contain as many apt-get packages as I want.
# Build your own if you want a smaller base.
# make pull requests if you want changes.
# time docker build -f Dockerfile-rolling . -t thesheff17/docker_base:rolling_latest-`date +"%m%d%Y"`
# time docker build -f Dockerfile-rolling . -t thesheff17/docker_base:rolling_latest

# build date
RUN echo `date` > /root/build_date.txt

# I use a local mirror to test
RUN echo 'Acquire::http::Proxy "http://172.17.0.1:3142";' > /etc/apt/apt.conf.d/01proxy

# fixes prompts
RUN \
    apt-get update && \
    apt-get -y upgrade && \
    apt-get install -y locales && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# helper ENV variables
RUN locale-gen en_US.UTF-8
ENV LANG en_US.UTF-8
ENV LANGUAGE en_US:en
ENV EDITOR vim
ENV SHELL bash
ENV DEBIAN_FRONTEND noninteractive

# 1 package per line/alphabetical order
RUN \
    dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y \
    apache2 \
    apt-transport-https \
    apt-utils \
    autoconf \
    automake \
    bison \
    build-essential \
    curl \
    fail2ban \
    gawk \
    git-core \
    gitk \
    gradle \
    htop \
    inetutils-ping \
    iptables \
    jq \
    lib32ncurses5 \
    lib32stdc++6 \
    lib32z1 \
    libapache2-mod-wsgi \
    libffi-dev \
    libgdbm-dev \
    libgmp-dev \
    libgmp-dev \
    libjpeg-dev \
    libmemcached-dev \
    libmysqlclient-dev \
    libncurses5-dev \
    libreadline6-dev \
    libsqlite3-dev \
    libssl-dev \
    libtool \
    libvirt-bin \
    libxml2-dev \
    libxslt1-dev \
    libyaml-dev \
    locate \
    lsb-release \
    lxc \
    mysql-client \
    net-tools \
    openjdk-8-jdk \
    openssl \
    python \
    python-dev \
    python-pip \
    python3-pip \
    qemu-kvm \
    screen \
    software-properties-common \
    sqlite3 \
    sudo \
    tmux \
    ubuntu-vm-builder \
    unzip \
    wget \
    xmlstarlet && \
    apt-get autoremove && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    rm /etc/apt/apt.conf.d/01proxy

WORKDIR /root/
CMD ["/bin/bash"]
